kind: pipeline
type: docker
name: image build

steps:

  - name: build latest
    image: plugins/docker
    environment:
      DOCKERHUB_ACCESS_TOKEN:
        from_secret: DOCKERHUB_ACCESS_TOKEN
    when:
      branch: master
    settings:
      username: mattbanner
      password: $DOCKERHUB_ACCESS_TOKEN
      repo: mattbanner/php-ci
      tags: latest

  - name: build develop
    image: plugins/docker
    environment:
      DOCKERHUB_ACCESS_TOKEN:
        from_secret: DOCKERHUB_ACCESS_TOKEN
    when:
      branch: develop
    settings:
      username: bannerbot
      password: $DOCKERHUB_ACCESS_TOKEN
      repo: mattbanner/php-ci
      tags: develop

  - name: build release
    image: plugins/docker
    environment:
      DOCKERHUB_ACCESS_TOKEN:
        from_secret: DOCKERHUB_ACCESS_TOKEN
    when:
      ref:
        - refs/tags/*
    settings:
      username: bannerbot
      password: $DOCKERHUB_ACCESS_TOKEN
      repo: mattbanner/php-ci
      tags: $DRONE_TAG
